### PR TITLE
Refreshing combat status and checking Gambits out of combat

### PR DESCRIPTION
**Pull request by hyskylord**
1. Refresh the combat time and check Gambits on every GamelogManager.MessageRecevied event, so that it can be fired out of Combat. This fixes many currently broken conditions such as Combat Time, In Combat/Out of Combat, use only once per combat etc.
2. Add CountdownTimer condition to Gambits, combining with the changes in 1 prepulls become possible (you can always add more conditions such as in instance to prevent false countdown)

### CODE REVIEW

**Comment by hyskylord** [comment]
Also some loggings are commented out since they are spammed right now

**Comment by cheesegoldfish** [comment]
It looks like magitek does get it's Heal pulsed by kombatant and atb even when out of combat (but not paused). 

I personally wouldn't want a gambit to trigger if kombatant / atb are in a paused state. If my botbase is paused, then magitek should be paused. I think listening to text events like this will break that guarantee.

It might be that, for every rotation, we need to add gambit & opener handling into the Heal task and remove it from the Combat task. Since the Heal task seems to be pulsed even when not strictly in combat.

**Comment by cheesegoldfish** [comment]
Moving the openers & gambits check into Heal instead of Combat seems to be promising, at least with openers.

**Comment by hyskylord** [comment]
I previously tested to refresh combat time in Utilities.Managers.RotationManager.Rotation.Heal() but it doesn't work. Maybe I accidently messed up something at that time. Would do more test to look into it.

**Comment by hyskylord** [comment]
@cheesegoldfish So I just made the test and it turns out that Heal() only get pulsed every 20 seconds outside of Combat and that's why my previous attempt didn't work. Might be a limit set by RB since I cannot find such code in ATB or Kombatant.

**Comment by cheesegoldfish** [comment]
Yeah that's odd... It's certainly pulsing these when I'm just sitting around in a sanctuary, 30 times per second. ATB. 

Trying to get to the same point where I can replicate what you have. 

```[08:58:23.841 N] [Magitek] Heal Pulsed
[08:58:23.841 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[08:58:23.873 N] [Magitek] Rest Pulsed
[08:58:23.873 N] [Magitek] PreCombatBuff Pulsed
[08:58:23.873 N] [Magitek] Heal Pulsed
[08:58:23.873 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[08:58:23.894 N] [Magitek] Rest Pulsed
[08:58:23.894 N] [Magitek] PreCombatBuff Pulsed
[08:58:23.894 N] [Magitek] Heal Pulsed
[08:58:23.894 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[08:58:23.924 N] [Magitek] Rest Pulsed
[08:58:23.924 N] [Magitek] PreCombatBuff Pulsed
[08:58:23.924 N] [Magitek] Heal Pulsed
[08:58:23.924 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[08:58:23.957 N] [Magitek] Rest Pulsed
[08:58:23.957 N] [Magitek] PreCombatBuff Pulsed
[08:58:23.957 N] [Magitek] Heal Pulsed
[08:58:23.957 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[08:58:24.009 N] [Magitek] Rest Pulsed
[08:58:24.009 N] [Magitek] PreCombatBuff Pulsed
[08:58:24.009 N] [Magitek] Heal Pulsed```

**Comment by cheesegoldfish** [comment]
Yep, the 20 seconds is a limit placed by RB. 

If you have a target that is an enemy and is attackable, it pulses at 30 ticks per second.

Seems like anything else, even a party member, and it only pulses once every 20 seconds. Unless... a log line is printed.

If a log line is printed in between pulses, it pulses at 30 ticks per second. 


I'm really actually feel like going crazy lol.

So I added a IF setting write log into Heal(). Then added it as a toggle so I could easily toggle it on and off.


```public static async Task<bool> Heal()
{
    if (PictomancerSettings.Instance.DebugState)
        Logger.WriteInfo("Heal Pulsed");

    if (Core.Me.IsMounted)
        return true;

    if (await Casting.TrackSpellCast()) return true;
    await Casting.CheckForSuccessfulCast();

    Casting.DoHealthChecks = false;

    if (await GambitLogic.Gambit()) return true;
    if (await CustomOpenerLogic.Opener()) return true;
    return false;

}```


With DebugState toggled on, it prints Heal Pulsed (out of combat, no target). back to back. See Looking For Item gambit keeps printing as well. So I know it's actually doing what it should be. 

With DebugState toggled off, there is no Heal Pulsed print. But then Looking For Item gambit only pulses once every 20 seconds! like... Am I crazy or what the actual blank? It's like all those stories I've heard about log statements changing how code works but I've never actually encountered it before. 

The fact that the actual log lines for Looking for Item also change, leads me to believe it really is a RB thing with log lines and not... something inside magitek? However clicking the toggle does immediately kick it out of the seemingly 20 second wait. I'm not quite sure how it knows to immediately pulse because the toggle setting changed. 

```[10:03:07.865 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:07.898 N] [Magitek] Heal Pulsed
[10:03:07.898 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:07.931 N] [Magitek] Heal Pulsed
[10:03:07.931 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:07.965 N] [Magitek] Heal Pulsed
[10:03:07.965 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:07.998 N] [Magitek] Heal Pulsed
[10:03:07.998 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:08.031 N] [Magitek] Heal Pulsed
>>> I pressed the toggle off here <<<
[10:03:08.031 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:28.032 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:03:48.065 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:04:08.098 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:04:28.131 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
[10:04:48.164 N] [Magitek] Looking for Item : Grade 8 Tincture of Intelligence
```

**Comment by hyskylord** [comment]
@cheesegoldfish So RB has a Logging.OnLogMessage event that might control pulses. My guess is that the actual implementation of ExecuteCoroutine() has some weird logic that refuses to execute the behavior even when pulsed.

**Comment by hyskylord** [comment]
I don't know how to solve this problem elegantly. Might need to also work with ATB and Kombatant as well.

One solution might be store the pause status of ATB and Kombatant into Core.TemporaryStorage, so that Magitek can detect it.

**Comment by cheesegoldfish** [comment]
Can you share a gambit condition that is currently broken so I can replicate the tests exactly too?

Even with it only pulsing once every 20 seconds with nothing going on, it does seem to pick up events like countdown and execute gambits immediately because it sees the countdown in the gamelog. 

So using these conditions in the opener 

image

It will cast even without a target exactly on time. 

What about also doing the gambits in the Pulse method of Magitek.cs? That still seems to be called every second, and it updates combat time/out of combat time and doesn't seem to be affected by this 20 second pause. & maybe only execute gambits in pulse if specifically not in combat. It does still have the issue that it could execute the gambit even though ATB is paused, but I think given the gambits that would be used outside of combat in this scenario, that is okay.

Or is there something broken about the Pulse() method that I am not understanding/replicating. 

I'd also be down with storing a temporary storage value and can add it for the ATB side, something like ... not sure about kombatant tho. 

```
Core.TemporaryStorage.CombatPausedState = MainSettingsModel.Instance.UsePause;
```

Just would like to replicate the exact scenario where a gambit doesn't work if the gambit/opener is placed in Heal() instead of Combat() of each jobs rotation.

**Comment by hyskylord** [comment]
My main problem was with the condition "Time in Combat" since I wanted to fix the timeline for mitigations. I don't think Pulse method will work since 
```
Combat.AdjustCombatTime();
```
was already there. Listening to the text event fixed it for me. Maybe it will be a solution to just remove the Gambit check from the text receive event, but still keep the adjust combat time functions.

**Comment by cheesegoldfish** [comment]
That seems a reasonable compromise for the moment. I think we might still need to handle openers & gambits in the Heal() of every job rotation for Countdown, but that can be done separately.

**Comment by hyskylord** [comment]
Actually I might be wrong to say that I have fixed it, since I haven't tested it in raids. It seems the Globals.PartyInCombat logic is a little bit suspicious too.
```
                    //In an instance, not autonomous
                    //Track every tagged or aggroed enemy in the vicinity
                    _enemyCache = GameObjectManager.GetObjectsOfType<BattleCharacter>().Where(r => (r.TaggerType > 0
                                                                                                       || r.HasTarget
                                                                                                       || r.IsBoss())
                                                                                                   && Core.Me.Distance(r) < 50)
                                                                                       .ToList();
```
This seems to list a boss as enemy even when actually out of combat.

**Comment by cheesegoldfish** [comment]
If Globals.PartyInCombat is an issue, seems reasonable that that should actually be checking the party, and not the enemies.

```
public static bool PartyInCombat => Core.Me.InCombat || Group.CastableAlliesWithin50.Any(ally => ally.InCombat);
```

**Comment by cheesegoldfish** [comment]
I found out why IsBoss is part of the enemies cache. 

Bosses often detarget the tank for transition mechanics, but the boss is still attackable. The IsBoss in the enemies cache is very important to keep the boss tracked as a valid enemy for Magitek while the boss is doing a transition (and has no target, and the taggerType is reset to 0 during the mechanic).

**Comment by hyskylord** [comment]
Maybe adding an InCombat check will fix the situation.
```
|| (r.IsBoss() && Core.Me.InCombat)
```

**Comment by cheesegoldfish** [comment]
👍

**Comment by cheesegoldfish** [comment]
I'm having some performance issues with this. 

Because GamelogManagerCountdownRecevied is called on every single message the game sends, this includes even when someone in novice network says something, as well as any battle log text.

Now that Tracking.Update is being called for every single battle message, it's causing noticeable slowdowns. 

CPU usage went from 0.7% to 1.7%-2.3%. Which on a 5.4ghz 32 core system cpu, that is not insignificant. I worry about multi-boxing especially on weaker/older machines. The more people & mobs around, the worse it is (testing this in fate farming). 

I think that's why Tracking.Update was done on a 1 second limiter in Pulse. It also appears to have something related to the fact that it is in the GameLogManager event. 

If I move that whole section to RotationManager.Heal(), so that it calls Tracking.Update() before going into the rotation, CPU usage is basically the same as before. 


I guess I still don't quite understand why Tracking.Update and AdjustCombatTime doesn't work for you when it's in the Pulse, but it can't stay in the GameLogManager event stream.

**Comment by hyskylord** [comment]
I removed it and it's working fine right now when I am outside of a party. I think the real thing to blame is PartyInCombat but I need to join some raids to test it.

**Comment by cheesegoldfish** [comment]
PartyInCombat being broken makes a lot of sense. I've noticed the routine picking up alliance raid bosses & stuff more reliably with that change in.

I'll go ahead and remove the code from that spot along with moving the gambits & openers to a central place for all routines. 

If it's still broken for you in raids i'll add it back, but i would like to get that partyincombat change out to everyone.

**Pull request merged**
