### PR TITLE
Reset Custom Openers properly

### PR DESCRIPTION
**Pull request by hyskylord**

### CODE REVIEW

**Comment by hyskylord** [comment]
Current issue: If the first action in the opener is a buff skill, then it will go to an infinite loop of starting and resetting the custom opener.

**Comment by hyskylord** [comment]
The specific case I want to solve is the map changes, so resetting on map change should be enough.

**Comment by cheesegoldfish** [comment]
Do you not get

```Resetting Openers Because We're Out Of Combat```

in log lines? It should be resetting openers just for being out of combat for 10 seconds.

**Comment by hyskylord** [comment]
```
CustomOpenerLogic._executedOpeners.Clear();
```
doesn't really cancel the current executing opener. A common situation I encounter is that if I enter the dungeon with an executing opener, Magitek will continue to execute the opener instead of resetting it.

**Pull request merged**
